apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    chart: ingress-nginx/ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 47.0.0
    helm:
      release-name: ingress-nginx
      values: |
        controller:
          kind: DaemonSet
          config:
            use-proxy-protocol: "true"
          service:
            annotations:
              load-balancer.hetzner.cloud/location: fsn1
              load-balancer.hetzner.cloud/name: load-balancer-1
              load-balancer.hetzner.cloud/use-private-ip: "true"
              load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
              load-balancer.hetzner.cloud/http-redirect-https: 'false'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
