apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    chart: ingress-nginx/ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.7.1
    helm:
      release-name: ingress-nginx
      valueFiles:
        - ingress/ingress-nginx-annotations.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
